name: Crypto Bot Auto Run

on:
  schedule:
    - cron: "*/5 * * * *"  # اجرای هر 5 دقیقه
  workflow_dispatch:        # اجرا دستی هم مجازه

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install requests feedparser pytz apscheduler

    - name: Run bot
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
        NEWS_FEED_URL: ${{ secrets.NEWS_FEED_URL }}
      run: python run_once.py
